mode: worker
worker:
  hostname: localhost
  port: 8086
server:
  hostname: localhost
  port: 8080
kafka:
  brokers: localhost:9092
  topic: monitoring-events-http-log
  producer:
    request.required.acks: -1
  consumer:
    auto.offset.reset: latest
    group.id: monitoring-events-http-log-consumer-0001
