mode: server
server:
  port: 8080
  host: localhost
kafka:
  brokers: localhost:9092
  topic: monitoring-events-http-log
  producer:
    request.required.acks: -1
  consumer:
    auto.offset.reset: latest
    group.id: monitoring-events-http-log-consumer-0001
